//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliotecaEntities : DbContext
    {
        public bibliotecaEntities()
            : base("name=bibliotecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AUTOR> AUTOR { get; set; }
        public virtual DbSet<EMPRESTIMO> EMPRESTIMO { get; set; }
        public virtual DbSet<EXEMPLAR> EXEMPLAR { get; set; }
        public virtual DbSet<LIVRO> LIVRO { get; set; }
        public virtual DbSet<MULTA> MULTA { get; set; }
        public virtual DbSet<PERFIL> PERFIL { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
    }
}
