//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPRESTIMO
    {
        public int id { get; set; }
        public System.DateTime dtEmprestimo { get; set; }
        public System.DateTime dtPrazoDevolucao { get; set; }
        public Nullable<System.DateTime> dtDevolucao { get; set; }
        public int fkUsuario { get; set; }
        public int fkExemplar { get; set; }
        public Nullable<int> fkMulta { get; set; }
    
        public virtual EXEMPLAR EXEMPLAR { get; set; }
        public virtual MULTA MULTA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
