//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class EXEMPLAR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EXEMPLAR()
        {
            this.EMPRESTIMO = new HashSet<EMPRESTIMO>();
        }
    
        public int id { get; set; }
        public bool perdido { get; set; }
        public TipoExemplar tipo { get; set; }
        public int fkLivro { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EMPRESTIMO> EMPRESTIMO { get; set; }
        public virtual LIVRO LIVRO { get; set; }
    }
}
