//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public int id { get; set; }
        public System.DateTime dtReserva { get; set; }
        public int fkLivro { get; set; }
        public int fkUsuario { get; set; }
    
        public virtual LIVRO LIVRO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
